// CareerOS/careeros-angular/src/app/shared/components/metric-block/metric-block.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

@Component({
  selector: 'app-metric-block',
  standalone: true,
  template: `
    <div class="nm-raised rounded-xl p-5" [class]="className">
      <p class="font-mono text-[10px] uppercase tracking-[0.08em] text-secondary">{{ label }}</p>
      <div class="mt-2 font-mono text-headline-lg font-medium text-primary" [style.view-transition-name]="transitionName || null">
        <ng-content>{{ value }}</ng-content>
      </div>
      @if (caption) {
        <p class="mt-1 font-label text-label-md text-secondary">{{ caption }}</p>
      }
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MetricBlockComponent {
  @Input() label = ''
  @Input() value = ''
  @Input() caption = ''
  @Input() transitionName = ''
  @Input() className = ''
}

// CareerOS/careeros-prototype/src/components/MetricBlock.jsx
export default function MetricBlock({ label, value, caption, valueClassName = "text-secondary" }) {
  return (
    <div>
      <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-txt-dim">{label}</p>
      <p className={`mt-1 font-mono text-3xl font-medium ${valueClassName}`}>{value}</p>
      {caption && <p className="mt-1 font-body text-xs text-txt-dim">{caption}</p>}
    </div>
  );
}
