// CareerOS/careeros-prototype/src/components/DataCard.jsx
export default function DataCard({ eyebrow, title, children, className = "", ...rest }) {
  return (
    <div className={`layer-raised rounded-2xl p-5 ${className}`} {...rest}>
      {eyebrow && (
        <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-txt-dim">
          {eyebrow}
        </p>
      )}
      {title && (
        <h3 className={`font-display text-lg font-bold text-secondary ${eyebrow ? "mt-1" : ""}`}>
          {title}
        </h3>
      )}
      {children && <div className={eyebrow || title ? "mt-3" : ""}>{children}</div>}
    </div>
  );
}

// CareerOS/careeros-angular/src/app/shared/components/data-card/data-card.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

@Component({
  selector: 'app-data-card',
  standalone: true,
  template: `
    <section class="nm-raised rounded-xl p-5" [class]="className">
      @if (eyebrow) {
        <p class="font-mono text-[10px] uppercase tracking-[0.08em] text-secondary">{{ eyebrow }}</p>
      }
      @if (title) {
        <h2 class="mt-2 font-display text-headline-sm font-semibold text-on-surface">{{ title }}</h2>
      }
      @if (caption) {
        <p class="mt-1 font-label text-label-md text-secondary">{{ caption }}</p>
      }
      <div [class.mt-4]="eyebrow || title || caption">
        <ng-content />
      </div>
    </section>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DataCardComponent {
  @Input() eyebrow = ''
  @Input() title = ''
  @Input() caption = ''
  @Input() className = ''
}
